### ISSUE TITLE
[yggtorrent] (testing) Exception (yggtorrent): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by tifo71** [FlareSolverr/FlareSolverr#1146]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.16
- Last working FlareSolverr version: 3.3.16
- Operating system: openMediaVault 7
- Are you using Docker: [yes/no] Yes 26
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
- Are you using a VPN: [yes/no] No
- Are you using a Proxy: [yes/no] No
- Are you using Captcha Solver: [yes/no] No
- If using captcha solver, which one:
- URL to test this issue: https://yggtorrent.qa
```

### Description

![image](https://github.com/FlareSolverr/FlareSolverr/assets/130233722/41522467-ca2c-4a14-81d0-892a8b211147)

There is a problem with flaresolverr. I use it via an OMV VM with portainer and jackett. According to the flaresolverr log it works but jackett puts this error in screen. I installed the previous version 3.3.15. But it still does the same thing.

I think flaresolverr has a bug. Everything was working fine and then suddenly nothing.

Flaresolverr 3.3.16 windows, on the other hand, works perfectly well.

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (yggtorrent): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid
```

### Screenshots

![image](https://github.com/FlareSolverr/FlareSolverr/assets/130233722/60ba4d4b-c9a5-48cc-97c2-ff2afdad2608)

as you can see in log flaresolverr work but jackett puts the error message in the logged error message section

**Comment by ilike2burnthing** [comment]
Follow the troubleshooting steps here - https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting

Failing that, read through https://github.com/FlareSolverr/FlareSolverr/issues/1139 to see if there's anything useful for you.

**Comment by MoryCorp** [comment]
Had the same issue.
Just updated both flaresolverr and prowlarr container.
YGGtorrent standalone works, not cookie.
But at least it works

Prowlarr : 

```
version: "3"
services:
  plex:
    restart: always
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/paris
    volumes:
        - ./config:/config
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prowlarr.rule=Host(`xxx.fr`)"
        - "traefik.http.routers.prowlarr.entrypoints=websecure"
        - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
    networks:
        - web

networks:
  web:
    external: true
```

Flaresolverr : 

```
version: "3.8"
services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
