### ISSUE TITLE
Error starting Chrome: Message: Can not connect to the Service /app/chromedriver

### ISSUE THREAD

**Issue by pops64** [FlareSolverr/FlareSolverr#1191]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:3.3.17
- Last working FlareSolverr version:Tried rolling back to 3.3.9
- Operating system:Linux 
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: tried with both
- Are you using a Proxy: no
- Are you using Captcha Solver: no
```

### Description

Clean install. I have tried every docker trick in the book and none seem to work. Tried with and with out a VPN(Using gluetun). Tried removing the container volume and recreating. Tried root and non root. Any time I try connecting to the container this error pops out(Via. It seems similar to #994 [Full Log](
https://pastebin.com/w8niLQSr) 

### Logged Error Messages

```text
2024-05-18 20:54:05 ERROR    Error starting Chrome: Message: Can not connect to the Service /app/chromedriver

Traceback (most recent call last):
  File "/app/utils.py", line 308, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "/app/utils.py", line 211, in get_webdriver
    return driver
           ^^^^^^
UnboundLocalError: cannot access local variable 'driver' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/flaresolverr.py", line 105, in <module>
    flaresolverr_service.test_browser_installation()
  File "/app/flaresolverr_service.py", line 72, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 314, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
```

**Comment by ilike2burnthing** [comment]
Is Docker update to date?

Provide the output for `uname -a` on your host device.

**Comment by pops64** [comment]
I update every Monday. I will let you know if that fixes the problem. As requested `Linux RyansStorageServer 6.8.9-arch1-2 #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:35:54 +0000 x86_64 GNU/Linux` And my docker compose incase I am overlooking a obvious error. I did try it without gluetun the same error in both cases
```
version: '3'
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
         #REMOVED for privacy#
      - 8191:8191 #flaresolverr
    volumes:
      - ./config/gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=#REMOVED for privacy#
      - VPN_TYPE=wireguard
      # Wireguard:
      - WIREGUARD_PRIVATE_KEY=#REMOVED for privacy#
      - WIREGUARD_ADDRESSES=#REMOVED for privacy#
      - SERVER_COUNTRIES=#REMOVED for privacy#
      - SERVER_CITIES=#REMOVED for privacy#
      - FIREWALL_OUTBOUND_SUBNETS=#REMOVED for privacy#
#REMOVED for privacy#
  # flaresolverr
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: "service:gluetun"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    restart: unless-stopped 
```

**Comment by ilike2burnthing** [comment]
So you have also tried creating the FlareSolverr container separate from Gluetun (`host` network, and its own port mapping)?

Just to be clear for Monday, as I realise I wasn't, I specifically mean updating the Docker program, not your Docker containers.

**Comment by pops64** [comment]
I tried 
```
flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: host
    ports:
      - "8191:8191"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    restart: unless-stopped 
```
Changed nothing. I tried again deleting the container volume. No luck. I then updated just docker. Went back to original config. No luck. I tried again using host mode in "". No luck. 

I run a system update every Monday. I have a watchtower container so my containers get updated within 24hrs of release.
