### ISSUE TITLE
Docker ARM64 - Chrome / Chromium version not detected!

### ISSUE THREAD

**Issue by Maximvdw** [FlareSolverr/FlareSolverr#1327]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: v3.3.21 | v3.3.20 | pr-1282
- Last working FlareSolverr version: N.a.
- Operating system: QNAP QTS
- Are you using Docker: yes
```

### Description

I have a QNAP ts-932px with an ARM Cortex-A57 (latest firmware from 16/08/2024). I use docker to run various containers but I am having difficulities getting flaresolverr running. I have 16GB RAM total with 11GB free. The flaresolverr container has no memory limits.

I tried 3.3.21, 3.3.20 and the latest pr-1282 docker tags. My error seems most related to: https://github.com/FlareSolverr/FlareSolverr/issues/687
Which seems to indicate that Chromium is crashing and hence not able to return a version. I have another docker container that uses chromium without issues for a different use case (creating PDFs from news sites)

docker compose:
```
version: "2.1"
services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:pr-1282
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Brussels
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
```

### Logged Error Messages

```text
flaresolverr  | 2024-08-17 01:35:25 INFO     FlareSolverr 3.3.21
flaresolverr  | 2024-08-17 01:35:25 INFO     Testing web browser installation...
flaresolverr  | 2024-08-17 01:35:25 INFO     Platform: Linux-4.2.8-aarch64-with-glibc2.31
flaresolverr  | 2024-08-17 01:35:25 INFO     Chrome / Chromium path: /usr/bin/chromium
flaresolverr  | Trace/breakpoint trap
flaresolverr  | 2024-08-17 01:35:25 ERROR    Chrome / Chromium version not detected!
```

NOTE with debug mode there is not much extra info

```text
024-08-17 12:24:11 INFO     ReqId 4396803910784 FlareSolverr 3.3.21
2024-08-17 12:24:11 DEBUG    ReqId 4396803910784 Debug log enabled
2024-08-17 12:24:11 INFO     ReqId 4396803910784 Testing web browser installation...
2024-08-17 12:24:11 INFO     ReqId 4396803910784 Platform: Linux-4.2.8-aarch64-with-glibc2.31
2024-08-17 12:24:11 INFO     ReqId 4396803910784 Chrome / Chromium path: /usr/bin/chromium
Trace/breakpoint trap
2024-08-17 12:24:11 ERROR    ReqId 4396803910784 Chrome / Chromium version not detected!
2024-08-17 12:24:39 INFO     ReqId 4396719893632 FlareSolverr 3.3.21
```

### Screenshots

![chrome_veiK5kCYVZ](https://github.com/user-attachments/assets/89795074-1727-4fb7-bac8-69a9d860c16d)
