### ISSUE TITLE
FlareSolverr was crash on PI5 (exec /usr/bin/dumb-init: input/output error)

### ISSUE THREAD

**Issue by dexter74** [FlareSolverr/FlareSolverr#1332]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: latest
- Last working FlareSolverr version: [NO]
- Operating system: Debian 12 on PI 5
- Are you using Docker: [yes]
- FlareSolverr User-Agent (see log traces or / endpoint): 
exec /usr/bin/dumb-init: input/output error
```

### Description

Hello,

When I start the container I get this error:

```
Architecture: aarch64
``` 

**Docker-compose**
```yml
version: '3.8'
services: 
 Flaresolverr:
  image: 'ghcr.io/flaresolverr/flaresolverr'
  platform: 'linux/arm64'
  container_name: 'flaresolverr'
  network_mode: 'bridge'
  restart: 'unless-stopped'
  hostname: 'flaresolverr'

  dns:
   - 8.8.8.8

  sysctls:
   net.ipv6.conf.all.disable_ipv6: 1

  environment:
   LOG_LEVEL:       'info'
   LOG_HTML:        'false' 
   CAPTCHA_SOLVER:  'none' 
   BROWSER_TIMEOUT: '2000'

  ports:
   - '8191:8191' 
``` 

### Logged Error Messages

```text
exec /usr/bin/dumb-init: input/output error
```

### Screenshots

![image](https://github.com/user-attachments/assets/9a4159e8-31ad-4d94-b423-b1ccef886cf1)
