### ISSUE TITLE
Using docker image 21hsmw/flaresolverr, container  is 1.2G RAM after 24h

### ISSUE THREAD

**Issue by caublet** [FlareSolverr/FlareSolverr#1387]
Try with this image, no need to modify the file anymore
21hsmw/flaresolverr:nodriver

;)

_Originally posted by @nanarCss in https://github.com/FlareSolverr/FlareSolverr/issues/1385#issuecomment-2408545656_

**Comment by nanarCss** [comment]
If you have issues with RAM, you can limit it via Docker.
With docker command : `docker run -m 512m --memory-swap 1g <container_name> ...`

Inside **docker-compose.yml**
```
deploy:
      resources:
        limits:
          memory: 512m
          memory_swap: 1g
```

By the way, I'm not having this issue ^^

```
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT     MEM %     NET I/O          BLOCK I/O       PIDS
454cb1c0f147   flaresolverr   0.01%     309.8MiB / 62.66GiB   0.48%     142MB / 19.4MB   415MB / 581MB   7
```
