### ISSUE TITLE
Unable to run Flaresolverr using Docker : Failed to connect

### ISSUE THREAD

**Issue by davinci-klod** [FlareSolverr/FlareSolverr#279]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**: latest
* **Operating system**: Raspberry Pi 3 Model B Rev 1.2 / 
* **Are you using Docker**: [Yes
* **Are you using a proxy or VPN?** No
* **Are you using Captcha Solver:** No

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

Hello,

I'm currently trying to install Flaresolverr using docker, but I'm running into several issues. I run the install and boot using the docker-compose method.

Here is the code launched by the command 'docker-compose up -d' :

```
---
version: "2.1"
services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped 
```

Flaresolverr seems to have launched, but when I want to use it it gets complicated.

At first, when I run the 'docker ps' command, I see that the container is launched, but it seems to be restarting in a loop because the status of Flaresolverr is always "Restarting ... seconds ago" . In addition to that, the port in use is not always displayed.

<img width="1352" alt="Capture d’écran 2022-01-17 à 10 57 58" src="https://user-images.githubusercontent.com/60784639/149748415-7f28994d-b95e-4281-a049-f8d2344b889a.png">

Secondly, when I want to use Flaresolverr as recommended with the example: 
```
curl -L -X POST 'http://192.168.17:8191/v1' \
-H 'Content-Type: application/json' \
--data-raw '{
  "cmd": "request.get",
  "url":"http://www.google.com/",
  "maxTimeout": 60000
}'
```

I have the following error message: 'curl: (7) Failed to connect to 192.168.1.7 port 8191: Connection refused'

Finally, when I consult the logs, nothing conclusive either:

```
#FailureMessage Object: 0x7e8d958c,
,
,
#,
# Fatal error in , line 0,
# unreachable code,
#,
#,
#,
#FailureMessage Object: 0x7ecbf58c,
,
,
#,
# Fatal error in , line 0,
# unreachable code,
#,
#,
#,
#FailureMessage Object: 0x7e8e358c,
,
,
#,
# Fatal error in , line 0,
# unreachable code,
#,
#,
#,
#FailureMessage Object: 0x7e8e658c,
,
,
#,
# Fatal error in , line 0,
# unreachable code,
#,
#,
#,
#FailureMessage Object: 0x7ea1d58c,
,
,
#,
# Fatal error in , line 0,
# unreachable code,
#,
#,
#,
#FailureMessage Object: 0x7ec2158c,
,
,
#,
# Fatal error in , line 0,
# unreachable code,
#,
#,
#,
#FailureMessage Object: 0x7efd758c,
,
,
#,
# Fatal error in , line 0,
# unreachable code,
#,
#,
#,
#FailureMessage Object: 0x7e81358c,
,
,
#,
# Fatal error in , line 0,
# unreachable code,
#,
#,
#,
#FailureMessage Object: 0x7e85c58c,
,
,
#,
# Fatal error in , line 0,
# unreachable code,
#,
#,
#,
#FailureMessage Object: 0x7ec0458c,
,
,
#,
# Fatal error in , line 0,
# unreachable code,
#,
#,
#,
#FailureMessage Object: 0x7ecc858c,
,
,
#,
# Fatal error in , line 0,
# unreachable code,
#,
#,
#,
#FailureMessage Object: 0x7eacb58c,
```

I'm new to Docker by the way, but everything I've been able to achieve so far except Flaresolverr user has been fine. I have several containers running without problems. The only modification made in portainer was to change the Public IP in the Endpoint menu. FlareSolverr is definitely not working for me although I followed all the installation steps.

Did you have an idea ?

Thanks :) !
