### ISSUE TITLE
Docker Compose Overrides or .env variables

### ISSUE THREAD

**Issue by JoshDi** [FlareSolverr/FlareSolverr#64]
### Environment

**FlareSolverr Version**: 1.2.2

**Docker**: [yes/no] yes

**OS**: Ubuntu 20.04 x64

**Last Working FlareSolverr Version**: 1.2.2

**Are you using a proxy or VPN?** [yes/no] yes

**Using Captcha Solver:** [yes/no] yes

**If using captcha solver, which one:** hcaptcha-solver

### Description

Can we please add a local folder that is ignored by GIT but allows us to override variables in the docker-compose.yml file? 
Other projects I use do this by adding a folder /local/compose with override files and by .env file with variable overrides

for example: .env file:

```
FLARESOLVERR_HOST=192.168.1.40
FLARESOLVERR_PORT=8191
COMPOSE_FILE=docker-compose.yml:local/compose/memory-settings.yml
```

The docker-compose.yml file can then have optional variable lookups if they are overriden by the .env file. This will help with updating our dockers but while still keeping our custom settings. 

```
- FLARESOLVERR_HOST=${FLARESOLVERR_HOST:-0.0.0.0}
- FLARESOLVERR_PORT=${FLARESOLVERR_PORT:-8191}
```

**Comment by ngosang** [comment]
>  Other projects I use do this by adding a folder /local/compose with override files and by .env file with variable overrides

Could you give me any example project?

If someone opens a PR I will accept it.

**Comment by JoshDi** [comment]
> > Other projects I use do this by adding a folder /local/compose with override files and by .env file with variable overrides
> 
> Could you give me any example project?
> 
> If someone opens a PR I will accept it.

[https://github.com/metabrainz/musicbrainz-docker](https://github.com/metabrainz/musicbrainz-docker)

**Comment by JoshDi** [comment]
Ok - sure. I am having trouble pushing the changes, but they are simple. 

**docker-compose.yml:**
```
---
version: "2.1"
services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      #- LOG_HTML=${LOG_HTML:-false}
      - HOST=${HOST:-0.0.0.0}
      # Used to change the verbosity of the logging
      - LOG_LEVEL=${LOG_LEVEL:-info}
      # Enables hcaptcha-solver => https://github.com/JimmyLaurent/hcaptcha-solver
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-None}
      #- CAPTCHA_SOLVER=hcaptcha-solver
      # Enables CaptchaHarvester => https://github.com/NoahCardoza/CaptchaHarvester
      #- CAPTCHA_SOLVER=harvester
      #- HARVESTER_ENDPOINT=https://127.0.0.1:5000/token
      #- HEADLESS=${HEADLESS:-true}
    ports:
      - ${PORT:-8191}:${PORT:-8191}
    restart: unless-stopped
```

Now in your **.env** file, you can override any values:
```
#HOST=192.168.1.55
PORT=8191
LOG_LEVEL=info
CAPTCHA_SOLVER=hcaptcha-solver
```

and view them via **docker-compose config**
```
services:
  flaresolverr:
    container_name: flaresolverr
    environment:
      CAPTCHA_SOLVER: hcaptcha-solver
      HOST: 0.0.0.0
      LOG_LEVEL: info
    image: ghcr.io/flaresolverr/flaresolverr:latest
    ports:
    - 8191:8191/tcp
    restart: unless-stopped
version: '2.1'
```
