### ISSUE TITLE
The cookies provided by FlareSolverr are not valid - IPv6

### ISSUE THREAD

**Issue by ilike2burnthing** [FlareSolverr/FlareSolverr#950]
I have ipv6 enabled in my docker setup. (In _/etc/docker/daemon.json_)

I had issues with iDope (timeout after 100s) and Ygg with Jackett:
``` The cookies provided by FlareSolverr are not valid```
and Prowlarr:
```Unable to connect to indexer, check the log above the ValidationFailure for more details. Login failed: No form found on https://www3.yggtorrent.wtf/ using form selector #user-login``` 
until I attached an ipv4 only network to flaresolverr and containers using it.

TorrentQQ, and Torrent[CORE] do work in both setups.

Relevant docker-compose v3 networking:
```yml
networks:
  ip4net:
    driver: bridge
    enable_ipv6: false
  ip64net:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: fdaa:5223:dbb1::/48
          gateway: fdaa:5223:dbb1::1
```

https://unique-local-ipv6.com/

_Originally posted by @pigsyn in https://github.com/FlareSolverr/FlareSolverr/issues/947#issuecomment-1800683357_
