### ISSUE TITLE
FlareSolverr Fails on Cloudflare-Protected Sites in Prowlarr Despite Successful Log

### ISSUE THREAD

**Issue by encryptedapple** [FlareSolverr/FlareSolverr#985]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [x] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.10
- Last working FlareSolverr version: none
- Operating system: Gentoo Linux
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint): {"msg": "FlareSolverr is ready!", "version": "3.3.10", "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"}
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

I have configured FlareSolverr in Prowlarr which when tested appears to work. However, whenever I test in on a website that has cloudflare protection, it fails says it fails in Prowlarr. The log says that it is successful which is odd. Thoughts on how to diagnose what the issue is? 

### Logged Error Messages

```text
2023-11-26 09:18:54 INFO     Challenge detected. Title found: Just a moment...
2023-11-26 09:18:58 INFO     Challenge solved!
2023-11-26 09:18:59 INFO     Response in 5.071 s
2023-11-26 09:18:59 INFO     127.0.0.1 POST http://localhost:31314/v1 200 OK
2023-11-26 09:19:03 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://torrentqq284.com/torrent/newest.html', 'proxy': {}}
```

### Screenshots

<img width="318" alt="image" src="https://github.com/FlareSolverr/FlareSolverr/assets/74748977/ae472069-9028-4424-8d4a-3099dc2483c8">

**Comment by encryptedapple** [comment]
Also docker-compose.yml:
```
services:
     flaresolverr:
         image: ghcr.io/flaresolverr/flaresolverr:latest
         container_name: flaresolverr
         environment:
           - LOG_LEVEL=${LOG_LEVEL:-info}
           - LOG_HTML=${LOG_HTML:-false}
           - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
           - TZ=UTC
           - PORT=31314
           - HOST=127.0.0.1
         network_mode: host
         pull_policy: always
         restart: unless-stopped
```

**Comment by ilike2burnthing** [comment]
Follow these troubleshooting steps - https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting

If you still have issues, remove the indexers in question, restart the Prowlarr and FlareSolverr containers, re-add the indexers (making sure to include the FlareSolverr tag), and test again.

If at that point you still have issues, add a Jackett container, configure FlareSolverr, test the same indexers.

**Comment by encryptedapple** [comment]
I ran through troubleshooting. Couldn't get it to work on Prowlarr. With no modification Jackett was able to add TorrentQQ first try. Might be an issue with Prowlarr. 

Edit: Indexes on Prowlarr that have a challenge of type: `Challenge detected. Title found: DDoS-Guard` have no problem being adding. The index I tried was AniDex for this purpose. It seems to have a problem any challenge that says `Challenge detected. Title found: Just a moment...` It's odd because the logs report success but Prowlarr doesn't see that.

**Comment by ilike2burnthing** [comment]
Adding the indexer on Jackett won't be the problem, you'll need to test them.

**Comment by encryptedapple** [comment]
Yes sorry. When it adds it auto tests the indexer. I also manually tested each indexer. Sorry for confusion.

**Comment by ilike2burnthing** [comment]
So to be clear:

1) there is no VPN or proxy used on your host, and you have not configured one to be used for either FlareSolverr or Prowlarr?

2) both FlareSolverr and Prowlarr are running in Docker and on the same device?

3) you have disable IPv6 either on your host or for both the FlareSolverr and Prowlarr containers?

4) both the FlareSolverr and Prowlarr containers are using the host network?

5) you have removed all problematic indexers from Prowlarr, restarted both the FlareSolverr and Prowlarr containers, attempted to re-add those indexers with the FlareSolverr tag, but they all fail in Prowlarr while showing as successful in FlareSolverr?

If that's the case, contact the Prowlarr team on their Discord (do NOT open an issue on their GitHub page). Direct them to this issue, and they should be able to walk you through some further troubleshooting, or may require trace logs from you.

**Comment by encryptedapple** [comment]
1. No VPN or proxy
2. FlareSolverr is running in docker with `network_mode: host` I am using a seedbox that auto setup Prowlarr not in a docker container. Perhaps tomorrow I will spin up a second instance of prowlarr in docker and see if that works. 
3. IPv6 is disabled for all localhost (127.0.0.1) communication. My hosting provider won't let me externally disable it. 
4. Yes, both are on the same network. 
5. Correct. 

I'll message them on Discord after I've done a bit more testing. I might spin up a second server that allows me to globally disable IPv6 and see if I can replicate the issue. May be a communication issue between docker container and localhost.

**Comment by ilike2burnthing** [comment]
Either both should be native or both should be in Docker.

With them both being in Docker, you can disable IPv6 for the containers rather than the whole host.

IPv6 being disabled for localhost communication isn't the goal, it's to prevent an initial request being made by Prowlarr using IPv4 but FlareSolverr using IPv6 (or vice versa), as then the cookie would be invalid.

**Comment by encryptedapple** [comment]
I wanted to post a follow up as I finally figured out what was going wrong. Hopefully this helps others. 

So essentially, as I am using a shared machine. I could not disable IPv6 on localhost. So my next step was to remove `network_mode: host` in my original docker compose and instead play around with the container localhost. However, that wasn't needed. I connected to the container by using hostname `flaresolverr` and then the port 8191. Everything worked as it should.

```
services:
     flaresolverr:
         image: ghcr.io/flaresolverr/flaresolverr:latest
         container_name: flaresolverr
         ports:
           - 31314:8191
         environment:
           - LOG_LEVEL=info
         pull_policy: always
         restart: unless-stopped
```
